com.library.base.path=/v1/library

# Validation
com.library.allowed-paths=\/bookings,\/bookings/[0-9]+,/users,/users/[0-9]+,/products,/products/[0-9]+,/orders,/orders/[0-9]+

# gRPC client
quarkus.grpc.clients.booking.host=localhost
quarkus.grpc.clients.booking.port=9000
quarkus.grpc.server.use-separate-server=false
quarkus.grpc.dev-mode.force-server-start=false